const {
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
} = process.env;
export const ENV = {
  CLOUDINARY_CLOUD_NAME: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: NEXT_PUBLIC_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  GOOGLE_MAPS_API_KEY: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
};
